### Computation Simulator
info:
  app:
    version: '@project.version@'

t2:
  computationSimulator:
    calculatePi:
      TotalPoints: ${T2_COMPUTATION_SIMULATOR_CALCULATE_PI_TOTAL_POINTS:100000000} # 100000000 → ~5 sec; 1000000000 → ~1 min
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: computation-simulator
    distribution:
      percentiles:
        all: 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

opentracing:
  jaeger:
    service-name: computation-simulator
    enabled: ${T2_JAEGER_ENABLED}
    udp-sender:
      host: ${T2_JAEGER_HOST}
