### Computation Simulator
# Dev profile
server:
  port: 8089

t2:
  computation-simulator:
    pi:
      totalPoints: 100000000 # 100000000 → ~5 sec; 1000000000 → ~1 min

opentracing:
  jaeger:
    service-name: computation-simulator
    enabled: false
    udp-sender:
      host: localhost

logging:
  level:
    de.unistuttgart.t2: DEBUG
