name: build and push docker image
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: check out parent
      uses: actions/checkout@v4
      with:
        repository: t2-project/microservices
        submodules: true
    - name: Ensure to use latest main from repo
      run: |
        git submodule update --init
        cd computation-simulator && git checkout main
    - name: Set up jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Maven build
      run: |
        chmod +x mvnw
        ./mvnw --projects computation-simulator --also-make clean install
    - run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Docker build and push (manual)
      run: |
        echo ${{ env.RELEASE_VERSION }}
        cd computation-simulator
        docker build -t t2project/computation-simulator:${{ env.RELEASE_VERSION }} .
        docker push t2project/computation-simulator:${{ env.RELEASE_VERSION }}
